# config.yaml
api_keys:
  #优先级：传参>yaml>环境变量
  anthropic: "YOUR_ANTHROPIC_API_KEY"
  openai: "sk-"
  openai_base_url: "http://rerverseapi.workergpt.cn/v1"
  bing_search: ""
  bing_search_url: "https://api.bing.microsoft.com/v7.0/search"
  jina: "jina_"

default_models:
  anthropic: "claude-3-7-sonnet-20250219"
  openai: "gpt-4o-2024-08-06"

runtime_parameters:
  model_provider: "openai"
  enable_crawler: false
  max_tokens: 8192
    #以下参数目前没有用上，实际上是写死的
  temperature: 0.7
  search_max_results: 5
  max_iterations: 3
